production:
  solr:
    hostname: 127.0.0.1
    port: 8080
    log_level: WARNING

development:
  solr:
    hostname: 127.0.0.1
    port: 8080
    log_level: INFO

test:
  solr:
    hostname: 127.0.0.1
    port: 8080
    log_level: WARNING
