source 'http://rubygems.org'

gem 'rails', '3.1.3'

# Postgres db adapter
gem 'pg'


# Gems used only for assets and not required
# in production environments by default.
# group :assets do
#   gem 'sass-rails',   '~> 3.1.4'
#   gem 'coffee-rails', '~> 3.1.1'
#   gem 'uglifier', '>= 1.0.3'
# end
gem "fog"
gem 'jquery-rails'
gem 's3'
#gem 'contacts', :git =>'git://github.com/cardmagic/contacts'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'
#gem 'image_optim'
#gem 'image_optim_pack'
  group :development do
  gem 'image_optim'
  end

# Use unicorn as the web server
 gem 'unicorn'
 gem 'fbgraph' 
#gem 'Sub-Engine',:require => "Sub-Engine", :path => '../Sub-Engine'
# Deploy with Capistrano
 gem 'capistrano'
gem 'active_merchant_ccavenue'
# To use debugger
#gem 'linecache19', :git => 'git://github.com/mark-moseley/linecache'
#gem 'ruby-debug-base19x', '~> 0.11.30.pre4'
gem 'daemons'
#gem 'ruby-debug19'
gem 'debugger'
gem "delayed_job", "~> 3.0.3" # To handle background jobs # document ---> http://rubydoc.info/gems/delayed_job/3.0.3/frames
gem 'delayed_job_active_record'
 #gem 'ruby-debug19','>= 0.5.11'
 #gem 'linecache19', :git => 'git://github.com/mark-moseley/linecache'
 #gem 'ruby-debug-base19x', '~> 0.11.30.pre4'
#gem 'jquery_datepicker'
group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

#gem added by kingston for testing purpose
#gem 'rails-dev-boost', :git =>'git://github.com/thedarkone/rails-dev-boost.git', :require =>'rails_development_boost'
# Kreatio Specific Gems
 gem 'icalendar'
 gem 'fastercsv','1.5.4'
 gem 'libxml-ruby'  # Fast XML parser
 gem 'nokogiri' # Parser
 gem 'sanitize','2.0.3' # To Sanitsie params
 gem 'rmagick' # For image processing uses image magick internally
 gem 'chronic','0.6.7' # Used for formatting Time 
 gem 'crack','0.3.1' # For Parsing XML and JSON
 gem 'acts_as_ferret', '>= 0.5' # Used for ferret search. Used for generating summary in Kreatio in search results.
 gem 'htmlentities','4.3.1' # Used for encoding and decoding HTML entities
 gem 'mime-types' # Used to find Mime Type of a file. Might have been used in file upload to identify the files type.
 gem 'builder','3.0.0' # XML Builder
 #gem 'net-ssh' # For SSH
 gem 'net-sftp','2.0.5' # For FTP
 gem 'xhtmldiff','1.0.0' # Takes a diff betweek two XHTML, planned to use for history function in articles 
 gem 'diff-lcs','1.1.3' # Takes a diff betweek two XHTML, planned to use for history function in articles 
 gem "xml-simple",'1.1.1' # Simple and easy XML parser.
 gem "mixable_engines",'0.1.1' # Planned to use multiple engine to override the Core Kreatio Kernel
 gem 'will_paginate', '>=3.0.pre' # Used for pagination
 gem 'memcache-client' # Used as API to store data in memcache.
 gem 'simple_captcha'
#gem 'galetahub-simple_captcha', :require => 'simple_captcha', :git => 'git://github.com/galetahub/simple-captcha.git'
# Used for building forms easily
 gem 'formtastic','2.0.2'

#Used for date picker
gem 'jquery_datepicker','0.3.4'

# Used for managing tree assosiations in active record.  
 gem 'acts_as_tree','0.1.1'
 gem 'sneaky-save'
# gem 'exception_notification','2.6.1'
gem 'Kreatio-Core', :path => '../Kreatio_Core'
 
 # simple captcha & recaptcha
 gem "recaptcha", :require => "recaptcha/rails"
 #gem 'galetahub-simple_captcha', :require => 'simple_captcha', :git => 'git://github.com/galetahub/simple-captcha.git'
 #gem 'json_builder'
 #gem 'rails_autolink'
 gem 'exception_notification','3.0.1'
 
 # Solr with Sunspot
 gem 'sunspot_rails'
 gem 'sunspot_solr'


  # datepicker for export import 
   gem 'calendar_date_select', :git => 'http://github.com/paneq/calendar_date_select.git', :branch => 'rails3test'
 
 #evetive calender
 gem 'icalendar'
 # Social media login
 gem "linkedin"
 gem "oauth"
# gem "rest-client"
 gem "json"
 gem 'render_with_missing_template' #render another template if render template is missing
 gem 'liquid','2.4.1'
 gem 'rest-client','1.6.7'
 gem "savon", "~> 1.2.0"


#gem added for the mail chimp
gem "feralchimp"

gem 'roo', '~> 2.0.0'
